version: '3.8'

services:
  ros-master:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ros-master
    ports:
      - "80:8080"     # Map container port 8080 to host port 80 (Web UI)
      - "9090:9090" # Map container port 9090 to host port 9090 (Rosbridge)
    volumes:
      - ./ros_ws/src:/home/robotuser/ws/src # Mount source code for live editing (optional but useful)
      - ./web:/home/robotuser/web # Mount web files for live editing
    environment:
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
